### ISSUE TITLE
[BUG] step2@Quickstart: local server clashed with error "zsh: bus error  lep photon run --name mygpt2 --local"

### ISSUE THREAD

**Issue by nidmgh** [leptonai/leptonai#318]
### step2@Quickstart: local server clashed with error "zsh: bus error  lep photon run --name mygpt2 --local"

1. following https://www.lepton.ai/docs/overview/quickstart
2. everything normal with local server up and runnging at /0.0.0.0:8080
3. execute the first request at step2. I tried command line curl, browser-based execution and and via Lepton's python clients. All crashed the sever

### environment: 
* Mac with Apple M1
* python 3 
* lepton 0.16.0

### server side

(base) user1@btf ~ % lep photon run --name mygpt2 --local

Launching photon on port: 8080
2024-02-02 12:27:02.451 | INFO     | leptonai.photon.hf.hf:pipeline:213 - Creating pipeline for text-generation(model=gpt2, revision=11c5a3d5).
HuggingFace download might take a while, please be patient...
2024-02-02 12:27:02.452 | INFO     | leptonai.photon.hf.hf:pipeline:218 - Note: HuggingFace caches the downloaded models in ~/.cache/huggingface/ (or C:\Users\<username>\.cache\huggingface\ on Windows). If you have already downloaded the model before, the download should be much faster. If you run out of disk space, you can delete the cache folder.
2024-02-02 12:27:05.760 | WARNING  | leptonai.photon.photon:_mount_route:928 - Skip mounting ui as `gradio` is not installed
2024-02-02 12:27:05.762 | INFO     | leptonai.photon.photon:_uvicorn_run:820 - Setting up signal handlers for graceful incoming traffic shutdown after 5 seconds.
2024-02-02 12:27:05,763 - INFO:
If you are using standard photon, a few urls that may be helpful:
	- http://0.0.0.0:8080/docs OpenAPI documentation
	- http://0.0.0.0:8080/redoc Redoc documentation
	- http://0.0.0.0:8080/openapi.json Raw OpenAPI schema
	- http://0.0.0.0:8080/metrics Prometheus metrics

If you are using python clients, here is an example code snippet:
	from leptonai.client import Client, local
	client = Client(local(port=8080))
	client.healthz()  # checks the health of the photon
	client.paths()  # lists all the paths of the photon
	client.method_name?  # If client has a method_name method, get the docstring
	client.method_name(...)  # calls the method_name method
If you are using ipython, you can use tab completion by typing `client.` and then press tab.

2024-02-02 12:27:05,767 - INFO:     Started server process [30338]
2024-02-02 12:27:05,767 - INFO:     Waiting for application startup.
2024-02-02 12:27:05.768 | INFO     | leptonai.photon.photon:uvicorn_startup:763 - Starting photon app - running startup prep code.
2024-02-02 12:27:05,768 - INFO:     Application startup complete.
2024-02-02 12:27:05,768 - INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
2024-02-02 12:28:58,488 - INFO:     127.0.0.1:49342 - "GET /openapi.json HTTP/1.1" 200 OK
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
**zsh: bus error  lep photon run --name mygpt2 --local**

### client side

```
# qs.py
# Via python client
from leptonai import Client
url = "http://localhost:8080"
client = Client(url)
print(client.run(inputs='Once upon a time'))
```

(base) user1@btf lepton % python qs.py
Traceback (most recent call last):
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 226, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user1/work/mycode/lepton/qs.py", line 5, in <module>
    print(client.run(inputs='Once upon a time'))
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/leptonai/client.py", line 468, in _method
    res = self._post(
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/leptonai/client.py", line 409, in _post
    return self._session.post(f"{self.url}/{path.lstrip('/')}", *args, **kwargs)
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpx/_client.py", line 1146, in post
    return self.request(
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpx/_client.py", line 828, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpx/_transports/default.py", line 230, in handle_request
    with map_httpcore_exceptions():
  File "/Users/user1/miniforge3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/user1/miniforge3/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

**Comment by nidmgh** [comment]
manually 
`$ pip install gradio` 
to get rid of the warning 
```
2024-02-02 12:27:05.760 | WARNING | leptonai.photon.photon:_mount_route:928 - Skip mounting ui as gradio is not installed
```

however, the same error still occurs

**Comment by Yangqing** [comment]
This looks a bit suspicious:

zsh: bus error lep photon run --name mygpt2 --local

It suggests that the local launch wasn't successful. Could you install the latest version and try again?

**Comment by nidmgh** [comment]
I uninstall/reinstall leptonai, and also used "conda" to create a new 'lepton' environment with python=3.11. The same problem still occurrs. 

It looks like exactly the same issue as https://github.com/leptonai/leptonai/issues/125, which indicated "[possible] be a hardware issue"
