### ISSUE TITLE
[BUG] KeyError while running lep deployment list

### ISSUE THREAD

**Issue by Stillerman** [leptonai/leptonai#378]
**Describe the bug**
After running
```
uv pip install -U leptonai && lep login
lep deployment list
```

I get 

```
Traceback (most recent call last):
  File "/Users/jts/daily/KismetAI/.venv/bin/lep", line 8, in <module>
    sys.exit(lep())
             ^^^^^
  File "/Users/jts/daily/KismetAI/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jts/daily/KismetAI/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/jts/daily/KismetAI/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jts/daily/KismetAI/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jts/daily/KismetAI/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jts/daily/KismetAI/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jts/daily/KismetAI/.venv/lib/python3.12/site-packages/leptonai/cli/deployment.py", line 62, in list_command
    d["name"],
    ~^^^^^^^^
KeyError: 'name'
```

**Environment (please complete the following information):**
 - OS: MacOS 14.0
 - Python version: 3.12.2
 - LeptonAI library version: lep, version 0.15.1

**Comment by bddppq** [comment]
Thanks for reporting. This is fixed in latest release (0.20.1), please do `pip install -U leptonai`.
