### ISSUE TITLE
WHY？

### ISSUE THREAD

**Issue by New-King** [leptonai/leptonai#424]
(env) root@VM-4-5-ubuntu:/home/search_with_lepton# python3 search_with_lepton.py
/home/search_with_lepton/env/lib/python3.10/site-packages/leptonai/photon/photon.py:605: RuntimeWarning: This photon expects secret GOOGLE_SEARCH_API_KEY, but it's not set. Please set it before running the photon, or you may get unexpected behavior.
  warnings.warn(
/home/search_with_lepton/env/lib/python3.10/site-packages/leptonai/photon/photon.py:605: RuntimeWarning: This photon expects secret SEARCHAPI_API_KEY, but it's not set. Please set it before running the photon, or you may get unexpected behavior.
  warnings.warn(
/home/search_with_lepton/env/lib/python3.10/site-packages/leptonai/photon/photon.py:605: RuntimeWarning: This photon expects secret LEPTON_WORKSPACE_TOKEN, but it's not set. Please set it before running the photon, or you may get unexpected behavior.
  warnings.warn(
Traceback (most recent call last):
  File "/home/search_with_lepton/env/lib/python3.10/site-packages/leptonai/client.py", line 472, in _raise_for_detailed_status
    detail = res.json()["error"]
  File "/home/search_with_lepton/env/lib/python3.10/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/home/search_with_lepton/env/lib/python3.10/site-packages/httpx/_models.py", line 570, in content
    raise ResponseNotRead()
httpx.ResponseNotRead: Attempted to access streaming response content, without having called `read()`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/search_with_lepton/search_with_lepton.py", line 644, in <module>
    rag.launch()
  File "/home/search_with_lepton/env/lib/python3.10/site-packages/leptonai/photon/photon.py", line 909, in launch
    self._call_init_once()
  File "/home/search_with_lepton/env/lib/python3.10/site-packages/leptonai/photon/photon.py", line 626, in _call_init_once
    self._init_res = self.init()
  File "/home/search_with_lepton/search_with_lepton.py", line 386, in init
    self.leptonsearch_client = Client(
  File "/home/search_with_lepton/env/lib/python3.10/site-packages/leptonai/client.py", line 334, in __init__
    if not self.healthz():
  File "/home/search_with_lepton/env/lib/python3.10/site-packages/leptonai/client.py", line 578, in healthz
    self._get_proper_res_content(res)
  File "/home/search_with_lepton/env/lib/python3.10/site-packages/leptonai/client.py", line 500, in _get_proper_res_content
    is_stream, non_stream_content = next(content)
  File "/home/search_with_lepton/env/lib/python3.10/site-packages/leptonai/client.py", line 486, in _generator
    self._raise_for_detailed_status(res)
  File "/home/search_with_lepton/env/lib/python3.10/site-packages/leptonai/client.py", line 474, in _raise_for_detailed_status
    detail = res.text
  File "/home/search_with_lepton/env/lib/python3.10/site-packages/httpx/_models.py", line 576, in text
    content = self.content
  File "/home/search_with_lepton/env/lib/python3.10/site-packages/httpx/_models.py", line 570, in content
    raise ResponseNotRead()
httpx.ResponseNotRead: Attempted to access streaming response content, without having called `read()`.

**Comment by wzhudev** [comment]
Hi. Since photon is already offline, I am closing this issue. Thanks.
