### ISSUE TITLE
lep login failed,  report:Invalid URL '/api/v1/workspace':

### ISSUE THREAD

**Issue by bruceguo123** [leptonai/leptonai#432]
**Describe the bug**
lep login failed.

**To Reproduce**
pip install -U leptonai && lep login

then report:
Traceback (most recent call last):
  File "/Users/damokeguo/Documents/projects/LLaMA-Factory/fac_env/bin/lep", line 8, in <module>
    sys.exit(lep())
  File "/Users/damokeguo/Documents/projects/LLaMA-Factory/fac_env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/damokeguo/Documents/projects/LLaMA-Factory/fac_env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/damokeguo/Documents/projects/LLaMA-Factory/fac_env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/damokeguo/Documents/projects/LLaMA-Factory/fac_env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/damokeguo/Documents/projects/LLaMA-Factory/fac_env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/damokeguo/Documents/projects/LLaMA-Factory/fac_env/lib/python3.10/site-packages/leptonai/cli/cli.py", line 146, in login
    info = api_client.info()
  File "/Users/damokeguo/Documents/projects/LLaMA-Factory/fac_env/lib/python3.10/site-packages/leptonai/api/v1/client.py", line 177, in info
    response = self._get("/workspace")
  File "/Users/damokeguo/Documents/projects/LLaMA-Factory/fac_env/lib/python3.10/site-packages/leptonai/api/v1/client.py", line 155, in _get
    return self._session.get(self.url + path, *args, **self._safe_add(kwargs))
  File "/Users/damokeguo/Documents/projects/LLaMA-Factory/fac_env/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/damokeguo/Documents/projects/LLaMA-Factory/fac_env/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/Users/damokeguo/Documents/projects/LLaMA-Factory/fac_env/lib/python3.10/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/Users/damokeguo/Documents/projects/LLaMA-Factory/fac_env/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/Users/damokeguo/Documents/projects/LLaMA-Factory/fac_env/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '/api/v1/workspace': No scheme supplied. Perhaps you meant https:///api/v1/workspace?

**Expected behavior**
login succeed.

**Screenshots**
<img width="1242" alt="image" src="https://github.com/leptonai/leptonai/assets/125955471/903b5123-4d3c-41d3-ae6f-c2525f01c63a">

**Environment (please complete the following information):**
 - OS: [mac OS，Sonoma 14.5 ]
 - Python version: [3.10.8]
 - LeptonAI library version: [0.21.1]

**Additional context**
someone others also meet this problem. see:https://github.com/leptonai/search_with_lepton/issues/85

**Comment by xlu451** [comment]
Thank you for submitting the issue. Here are some steps to resolve it:

1. Register an account and open your workspace at [lepton.ai](https://www.lepton.ai/).
2. Ensure you are using the latest version of the `leptonai` package by running:
   ```bash
   pip install --upgrade leptonai
   ```
3. List your workspaces with:
   ```bash
   lep workspace list
   ```
4. Remove the local workspace with the error:
   ```bash
   lep workspace remove -i <your-local-workspace-id-with-this-error>
   ```
5. Log in again:
   ```bash
   lep login
   ```
   Copy the credentials and paste the credentials in command prompt

   If you already know your credentials (which you can find in your workspace settings under tokens), you can also use:
   ```bash
   lep login -c your_workspace_id:your_token
   ```

If the issue persists, please reach out for assistance.

**Comment by bruceguo123** [comment]
Thx, the problem has been solved. May I ask what caused the problem? Was it because of my incorrect operation?

**Comment by xlu451** [comment]
Nice! 
Did you successfully log in previously, and did deleting your local workspace resolve the problem? 
Or is this your first time trying to log in?

**Comment by bruceguo123** [comment]
No，never login successfully。
and  I deleted local workspace, and then succeed.

**Comment by xlu451** [comment]
Did you set up this workspace yourself, or did it appear when you typed lep login?

**Comment by bruceguo123** [comment]
No，I did not。
the first time I typed lep login, it asked me to input authentication token。 I inputed, but lep login failed.
from that moment on, every time I try lep login, it just failed, did not ask me input authentication token any more.

**Comment by xlu451** [comment]
I see, it looks like you only provided the authentication token. Actually, the CLI requires the credential in this format: <workspace_id>:<auth_token>. No worries, we’ve upgraded to a safer login method, and I’ll add a user hint to inform everyone about the correct credential format. Thank you so much for your help!

**Comment by bruceguo123** [comment]
also thank u.
this project helped me a lot!
