### ISSUE TITLE
[BUG] "KeyError: 'type' When Launching Photon with Local Model vllm:Meta-Llama-3.1-70B-Instruct-AWQ-INT4

### ISSUE THREAD

**Issue by shiertier** [leptonai/leptonai#511]
**Describe the bug**
When attempting to launch the lep ph runlocal command with the specified model vllm:Meta-Llama-3.1-70B-Instruct-AWQ-INT4, the process fails with a KeyError: 'type'. This prevents the photon from starting up successfully.

**To Reproduce**
   ```bash
   lep ph runlocal \
       -n llama \
       -m vllm:Meta-Llama-3.1-70B-Instruct-AWQ-INT4
   ```

**Expected behavior**
The expected behavior is for the photon to rebuild with the specified model and launch successfully without any KeyError.

**Environment (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - Python version: [3.10]
 - LeptonAI library version: [0.22.0]
 - vLLM library version: [5.2]

**Additional context**

Here is the error report.
```
If you want to run without rebuilding, please remove the --model arg.
Photon llama created.
Launching photon on port: 8080
2024-10-09 13:33:56.152 | INFO     | leptonai.photon.photon:run_server:926 - Launching liveness server on port 8765
/root/miniconda3/envs/lepton/lib/python3.10/site-packages/leptonai/photon/photon.py:616: RuntimeWarning: This photon expects secret HUGGING_FACE_HUB_TOKEN, but it's not set. Please set it before running the photon, or you may get unexpected behavior.
  warnings.warn(
2024-10-09 13:34:06.736 | DEBUG    | leptonai.photon.vllm.vllm:init:82 - Overriding model id with VLLM_MODEL: Meta-Llama-3.1-70B-Instruct-AWQ-INT4.
2024-10-09 13:34:06.823 | INFO     | leptonai.photon.vllm.vllm:init:110 - Using tensor_parallel_size=8
Failed to launch photon: <class 'KeyError'>: 'type'
Traceback:
Traceback (most recent call last):
  File "/root/miniconda3/envs/lepton/lib/python3.10/site-packages/leptonai/cli/photon.py", line 574, in runlocal
    photon.launch(port=port)
  File "/root/miniconda3/envs/lepton/lib/python3.10/site-packages/leptonai/photon/photon.py", line 946, in launch
    self._call_init_once()
  File "/root/miniconda3/envs/lepton/lib/python3.10/site-packages/leptonai/photon/photon.py", line 647, in _call_init_once
    self._init_res = self.init()
  File "/root/miniconda3/envs/lepton/lib/python3.10/site-packages/leptonai/photon/vllm/vllm.py", line 121, in init
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/root/miniconda3/envs/lepton/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 457, in from_engine_args
    engine_config = engine_args.create_engine_config()
  File "/root/miniconda3/envs/lepton/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 699, in create_engine_config
    model_config = ModelConfig(
  File "/root/miniconda3/envs/lepton/lib/python3.10/site-packages/vllm/config.py", line 176, in __init__
    self.max_model_len = _get_and_verify_max_len(
  File "/root/miniconda3/envs/lepton/lib/python3.10/site-packages/vllm/config.py", line 1497, in _get_and_verify_max_len
    if rope_scaling is not None and rope_scaling["type"] not in {
KeyError: 'type'
```

**Comment by wzhudev** [comment]
Hi. Since photon is already offline, I am closing this issue. Thanks.
